config/routes.rb
Rails.application.routes.draw do
  resources :short_url

  root "short_url#new"
  get ':unique_string', :to => 'short_url#show'

end

app/models/short_url_list.rb
class ShortUrlList < ActiveRecord::Base
  validates_presence_of :redirect_to
  #before_create 資訊請參考https://ihower.tw/rails4/activerecord-lifecycle.html 中的call back
  before_create :random_unique_string

  private
  def random_unique_string
    unique_string = SecureRandom.hex(5)
    while ShortUrlList.find_by_unique_string( unique_string ).present? do
      unique_string = SecureRandom.hex(5)
    end
    self.unique_string = unique_string
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/short_url_controller.rb
class ShortUrlController < ApplicationController
  before_action :set_params, :only => :create

  def new
    @short_url = ShortUrlList.new
  end

  def create
    @short_url = ShortUrlList.find_by_redirect_to(set_params["redirect_to"]) || ShortUrlList.new(set_params)
    if @short_url.new_record?
      if !@short_url.save
        # ActiveRecord validates 錯誤訊息使用方式參考
        # http://guides.rubyonrails.org/active_record_validations.html#working-with-validation-errors
        render :new
      end
    end
  end
  def show
    # set_unique_string是一個Hash Parameters: {"unique_string"=>"959ee2a935"}
    # 運用find_by 放入一個Hash會產生的SQL語法
    # SELECT  "short_url_lists".* FROM "short_url_lists" WHERE "short_url_lists"."unique_string" = ? LIMIT 1  [["unique_string", "959ee2a935"]]
    @short_url = ShortUrlList.find_by(set_unique_string)
    if @short_url.present?
      @short_url.increment(:count).save
      # redirect_to @short_url.redirect_to
    else
      flash[:notice]='Short Url is not exist!'
      redirect_to new_short_url_url
    end
  end
  private
  def set_params
    params.require(:short_url_list).permit(:redirect_to)
  end
  def set_unique_string
    params.permit(:unique_string)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/short_url_helper.rb
module ShortUrlHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShortUrlExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/short_url/create.html.erb
<div class="panel panel-default devise-bs">
  <div class="panel-heading">
    <h4>短網址</h4>
  </div>
  <div class="panel-body">
    <h5>網址：<%=  link_to request.host_with_port + '/' + @short_url.unique_string , "http://"+request.host_with_port + '/' + @short_url.unique_string %></h5>
  </div>
  <div class="panel-body">
    <%= button_to "Short Url Generate", new_short_url_path , :class => "btn btn-success", :method => :get %>
  </div>
</div>

app/views/short_url/new.html.erb
<div class="panel panel-default devise-bs">
  <% if @short_url.errors.any? %>
      <ul>
        <% @short_url.errors.full_messages.each do |msg| %>
            <li style="color:red"><%= msg %></li>
        <% end %>
      </ul>
  <% end %>
  <div class="panel-heading">
    <h4>產生短網址</h4>
  </div>
  <div class="panel-body">
    <%= form_for @short_url, :url => short_url_index_path(), :method => 'post' do |f| %>
        <div class="form-group">
          <%= f.label :redirect_to %>
          <%= f.url_field :redirect_to, autofocus: true, class: "form-control" %>
        </div>
        <%= f.submit "產生短網址", class: "btn btn-primary" %>
    <% end %>
  </div>
  <div class="panel-body">
    <h5><%= notice %></h5>
  </div>
</div>

app/views/short_url/show.html.erb
<div class="panel panel-default devise-bs">
  <div class="panel-heading">
    <h4>轉跳中</h4>
  </div>
  <div class="panel-body">
    第<%= @short_url.count %>次轉址到<%= link_to @short_url.redirect_to %><br/>
    5秒後自動轉跳
    <script>window.setTimeout("location.href='<%= @short_url.redirect_to %>'", 5000);</script>
  </div>
</div>